### ISSUE TITLE
[BUG] Launcher tries to make a directory in an inaccessible location

### ISSUE THREAD

**Issue by Gooberpatrol66** [FlashpointProject/launcher#144]
**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10] linux
 - Flashpoint Version [e.g. 7.1] 8.1
 - Log text (if relevant) 

```
nathan@gentoodesktop ~ $ /opt/F*/*/L*/flashpoint-launcher
Gtk-Message: 12:36:22.068: Failed to load module "appmenu-gtk-module"
{ args: {}, rest: '' }
(node:187930) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/home/Data'
(node:187930) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/home/Data'
(node:187930) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:187930) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:187930) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:187930) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^CFailed to send message! There is no socket! (ID: "c081b9e0-3464-4f2d-bdb5-94adf6cb1777", Type: 35 / "QUIT")
An error occurred whie closing the file server. Error [ERR_SERVER_NOT_RUNNING]: Server is not running.
    at Server.close (net.js:1591:12)
    at Object.onceWrapper (events.js:299:28)
    at Server.emit (events.js:210:5)
    at emitCloseNT (net.js:1644:8)
    at processTicksAndRejections (internal/process/task_queues.js:79:21) {
  code: 'ERR_SERVER_NOT_RUNNING'
}
Error: Failed to close server. No server is open.
    at /opt/Flashpoint Infinity/Flashpoint 8.1 Infinity/Launcher/resources/app.asar/build/back/SocketServer.js:84:24
    at new Promise (<anonymous>)
    at SocketServer.close (/opt/Flashpoint Infinity/Flashpoint 8.1 Infinity/Launcher/resources/app.asar/build/back/SocketServer.js:72:16)
    at Object.exit (/opt/Flashpoint Infinity/Flashpoint 8.1 Infinity/Launcher/resources/app.asar/build/back/util/misc.js:132:32)
    at process.<anonymous> (/opt/Flashpoint Infinity/Flashpoint 8.1 Infinity/Launcher/resources/app.asar/build/back/index.js:91:41)
    at process.emit (events.js:210:5)
    at finish (internal/child_process.js:861:14)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

```

**Additional context**

**Comment by colin969** [comment]
Try changing the flashpointPath var in config.json to point to the folder you want manually.

Also given the error loading the module, try installing `appmenu-gtk2-module` and `appmenu-gtk3-module`

**Comment by Gooberpatrol66** [comment]
The path I put is... truncated?

"flashpointPath": "/opt/Flashpoint Infinity/Flashpoint 8.1 Infinity/Data"

```
nathan@gentoodesktop ~/Documents/projects/gooby-overlay/gooby-overlay/nathan/flashpoint $ /opt/F*/L*/flashpoint-launcher
{ args: {}, rest: '' }
(node:1492788) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/opt/Flashpoint Infinity'
(node:1492788) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/opt/Flashpoint Infinity'
(node:1492788) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1492788) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1492788) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1492788) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by colin969** [comment]
Looks like it's lacking the permissions to create or view it. Change the folder perms of /opt/Flashpoint Infinity/

**Comment by Gooberpatrol66** [comment]
Fixed with permissions change.

**Comment by LeSnake04** [comment]
> Fixed with permissions change.

cant you please say what permision you changed to fix it?
