### ISSUE TITLE
[BUG] Error: Preferences must be set before you can open a window.

### ISSUE THREAD

**Issue by Endercheif** [FlashpointProject/launcher#175]
**Error** 
Uncaught Exception:
Error: Preferences must be set before you can open a window.
    at createMainWindow (/Applications/Flashpoint.app/Contents/Resources/app.asar/build/main/Main.js:312:19)
    at App.onAppActivate (/Applications/Flashpoint.app/Contents/Resources/app.asar/build/main/Main.js:275:28)
    at App.emit (events.js:210:5)

**To Reproduce**
1. Download the latest flashpoint version for mac
2. Try to run it
4. See error popup

**Expected behavior**
For the program to start

**Screenshots**
![Screen Shot](https://user-images.githubusercontent.com/45527309/103799471-fc1dd380-4fff-11eb-9385-70bfb6fdaf1e.png)

**Desktop:**
 - Mac OS Catalina 10.15.6
 - Macbook Air 2017
 - Flashpoint Version (Latest Release)

**Comment by Endercheif** [comment]
I didn't the read page well enough and downloaded the wrong thing for me
