### ISSUE TITLE
[BUG] Launcher does not start when preferences.json exists but is empty

### ISSUE THREAD

**Issue by n0samu** [FlashpointProject/launcher#238]
**Describe the bug**
If the preferences.json file exists but is empty, then the launcher process shows up in Task Manager, but the window never appears. Here is the output when running Flashpoint from the Command Prompt:
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at C:\Users\nosamu\Flashpoint\Flashpoint Core 10\Launcher\resources\app.asar\build\shared\Util.js:29:39
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
Error: Failed to close server. No server is open.
    at C:\Users\nosamu\Flashpoint\Flashpoint Core 10\Launcher\resources\app.asar\build\back\SocketServer.js:50:24
    at new Promise (<anonymous>)
    at SocketServer.close (C:\Users\nosamu\Flashpoint\Flashpoint Core 10\Launcher\resources\app.asar\build\back\SocketServer.js:38:16)
    at Object.exit (C:\Users\nosamu\Flashpoint\Flashpoint Core 10\Launcher\resources\app.asar\build\back\util\misc.js:134:32)
    at process.onProcessMessage (C:\Users\nosamu\Flashpoint\Flashpoint Core 10\Launcher\resources\app.asar\build\back\index.js:253:16)
An error occurred while closing the file server. Error [ERR_SERVER_NOT_RUNNING]: Server is not running.
    at Server.close (net.js:1591:12)
    at Object.onceWrapper (events.js:299:28)
    at Server.emit (events.js:210:5)
    at emitCloseNT (net.js:1644:8)
    at processTicksAndRejections (internal/process/task_queues.js:79:21) {
  code: 'ERR_SERVER_NOT_RUNNING'
}
```

**Expected behavior**
Expected the launcher to generate a default set of preferences and start correctly.

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - Flashpoint Version: Core 10

**Additional context**
This is a problem mainly because the launcher's preferences are sometimes wiped. I described this in #239.

**Comment by n0samu** [comment]
I just checked the launcher still fails to show its window if preferences.json is empty.

**Comment by LindirQuenya** [comment]
This needs to be reopened - this issue isn't that the preferences.json can become 0kb, it's that the launcher will hang if it does.
