### ISSUE TITLE
[BUG] Build fails on Node 17 - electron/sqlite issue?

### ISSUE THREAD

**Issue by LindirQuenya** [FlashpointProject/launcher#290]
**Describe the bug**
When building the launcher with Node 17, the build fails with some error about an s3 bucket. This looks like an electron or maybe sqlite problem, but perhaps it merits a note in the README.

**To Reproduce**
1. Install Node 17.x
2. Clone the repo as shown in the README
3. run `npm install`
4. After a bit of dependency-fetching, it will spit out the error.

**Expected behavior**
The launcher builds nicely without any errors. This is the behavior for Node 16.x.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Xubuntu 21.10 Impish Indri
 - Flashpoint Version: develop @ b0df1ad
 - Log text (if relevant)
```
> flashpoint-launcher@10.1.1 postinstall
> electron-builder install-app-deps

  • electron-builder  version=22.11.7
  • rebuilding native dependencies  dependencies=sqlite3@4.2.0 platform=linux arch=x64
  ⨯ cannot execute  cause=exit status 1
                    errorOut=npm ERR! code 1
    npm ERR! path /home/jeb/Documents/GitHub/Flashpoint/launcher/node_modules/sqlite3
    npm ERR! command failed
    npm ERR! command sh -c node-pre-gyp install --fallback-to-build
    npm ERR! Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/jeb/Documents/GitHub/Flashpoint/launcher/node_modules/sqlite3/lib/binding/electron-v12.2-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/jeb/Documents/GitHub/Flashpoint/launcher/node_modules/sqlite3/lib/binding/electron-v12.2-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v12.2' (1)
    npm ERR! node-pre-gyp info it worked if it ends with ok
    npm ERR! node-pre-gyp info using node-pre-gyp@0.11.0
    npm ERR! node-pre-gyp info using node@17.3.0 | linux | x64
    npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download 
    npm ERR! node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/electron-v12.2-linux-x64.tar.gz
    npm ERR! node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/electron-v12.2-linux-x64.tar.gz
    npm ERR! node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/electron-v12.2-linux-x64.tar.gz 
    npm ERR! node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.2.0 and electron@12.2.1 (electron-v12.2 ABI, glibc) (falling back to source compile with node-gyp) 
    npm ERR! node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/electron-v12.2-linux-x64.tar.gz 
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@8.4.1
    npm ERR! gyp info using node@17.3.0 | linux | x64
    npm ERR! gyp info ok 
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@8.4.1
    npm ERR! gyp info using node@17.3.0 | linux | x64
    npm ERR! gyp info find Python using Python version 3.9.7 found at "/usr/bin/python3"
    npm ERR! gyp info spawn /usr/bin/python3
    npm ERR! gyp info spawn args [
    npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
    npm ERR! gyp info spawn args   'binding.gyp',
    npm ERR! gyp info spawn args   '-f',
    npm ERR! gyp info spawn args   'make',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/home/jeb/Documents/GitHub/Flashpoint/launcher/node_modules/sqlite3/build/config.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/home/jeb/.electron-gyp/12.2.1/include/node/common.gypi',
    npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
    npm ERR! gyp info spawn args   '-Dvisibility=default',
    npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/jeb/.electron-gyp/12.2.1',
    npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
    npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/jeb/.electron-gyp/12.2.1/<(target_arch)/node.lib',
    npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/jeb/Documents/GitHub/Flashpoint/launcher/node_modules/sqlite3',
    npm ERR! gyp info spawn args   '-Dnode_engine=v8',
    npm ERR! gyp info spawn args   '--depth=.',
    npm ERR! gyp info spawn args   '--no-parallel',
    npm ERR! gyp info spawn args   '--generator-output',
    npm ERR! gyp info spawn args   'build',
    npm ERR! gyp info spawn args   '-Goutput_dir=.'
    npm ERR! gyp info spawn args ]
    npm ERR! gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp
    npm ERR! gyp ERR! configure error 
    npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
    npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:259:16)
    npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
    npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
    npm ERR! gyp ERR! System Linux 5.13.0-22-generic
    npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/jeb/Documents/GitHub/Flashpoint/launcher/node_modules/sqlite3/lib/binding/electron-v12.2-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/jeb/Documents/GitHub/Flashpoint/launcher/node_modules/sqlite3/lib/binding/electron-v12.2-linux-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v12.2"
    npm ERR! gyp ERR! cwd /home/jeb/Documents/GitHub/Flashpoint/launcher/node_modules/sqlite3
    npm ERR! gyp ERR! node -v v17.3.0
    npm ERR! gyp ERR! node-gyp -v v8.4.1
    npm ERR! gyp ERR! not ok 
    npm ERR! node-pre-gyp ERR! build error 
    npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/jeb/Documents/GitHub/Flashpoint/launcher/node_modules/sqlite3/lib/binding/electron-v12.2-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/jeb/Documents/GitHub/Flashpoint/launcher/node_modules/sqlite3/lib/binding/electron-v12.2-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v12.2' (1)
    npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/jeb/Documents/GitHub/Flashpoint/launcher/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
    npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
    npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1062:16)
    npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
    npm ERR! node-pre-gyp ERR! System Linux 5.13.0-22-generic
    npm ERR! node-pre-gyp ERR! command "/usr/bin/node" "/home/jeb/Documents/GitHub/Flashpoint/launcher/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
    npm ERR! node-pre-gyp ERR! cwd /home/jeb/Documents/GitHub/Flashpoint/launcher/node_modules/sqlite3
    npm ERR! node-pre-gyp ERR! node -v v17.3.0
    npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.11.0
    npm ERR! node-pre-gyp ERR! not ok
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/jeb/.npm/_logs/2021-12-29T21_00_24_004Z-debug-0.log
    
                    command=/usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js rebuild sqlite3@4.2.0
                    workingDir=
npm ERR! code 1
npm ERR! path /home/jeb/Documents/GitHub/Flashpoint/launcher
npm ERR! command failed
npm ERR! command sh -c electron-builder install-app-deps

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jeb/.npm/_logs/2021-12-29T21_00_19_324Z-debug-0.log
```
**Additional context**

**Comment by LindirQuenya** [comment]
This is indeed electron's fault, see here: https://www.electronjs.org/releases/stable.
The latest stable is 16.x.
