### ISSUE TITLE
[BUG] Unable to build on Windows - esbuild version error

### ISSUE THREAD

**Issue by dot-mike** [FlashpointProject/launcher#438]
**Describe the bug**
I am unable to build on Windows 11 using Node v22.11.0 (LTS). Same issue with v20.18.1 (LTS) on MAIN branch.

**To Reproduce**
1. Clone repo on Windows and setup repo with `git submodule update --init --recursive`
2. run `npm install`
3. See NPM error: `Error: Expected "0.20.2" but got "0.19.12"` in console output.

**Expected behavior**
Installation of NPM modules to be successfull.

**Error message**
```
npm error code 1
npm error path C:\Users\mike\Documents\GitHub\launcher\extensions\core-curation\node_modules\esbuild
npm error command failed
npm error command C:\Windows\system32\cmd.exe /d /s /c node install.js
npm error C:\Users\mike\Documents\GitHub\launcher\extensions\core-curation\node_modules\esbuild\install.js:133
npm error     throw new Error(`Expected ${JSON.stringify(versionFromPackageJSON)} but got ${JSON.stringify(stdout)}`);
npm error           ^
npm error
npm error Error: Expected "0.20.2" but got "0.19.12"
npm error     at validateBinaryVersion (C:\Users\mike\Documents\GitHub\launcher\extensions\core-curation\node_modules\esbuild\install.js:133:11)
npm error     at C:\Users\mike\Documents\GitHub\launcher\extensions\core-curation\node_modules\esbuild\install.js:284:5
npm error
npm error Node.js v22.11.0
```

Debug log from NPM:
[2024-11-26T23_11_00_604Z-debug-0.log](https://github.com/user-attachments/files/17926685/2024-11-26T23_11_00_604Z-debug-0.log)

**Comment by dot-mike** [comment]
Navigating to the directory `extensions\core-curation` and running `npm install esbuild@0.20.2 --force` seems to the problem. onl then `npx gulp extInstall` succeed without issues.
